[tool.poetry]
name = "project01"
version = "0.1.0"
description = ""
authors = ["thomas0376 <thomas.prevarin@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.6"
pandas = "2.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
